Use supersede_metadata to perfom metadata updates on ont collections
wtsi-npg/npg-irods-python pull request #138
Opened 2023-05-11 10:01 UTC by mksanger

2023-05-11 11:43 UTC, kjsanger requested changes
The tests for the history metadata are nice - much more thorough than in partisan. At some point tests of this kind (perhaps these) should migrate to partisan because that's where the implementation is. Having them here for now is pragmatic - I approve.

2023-05-11 11:43 UTC, kjsanger commented on tests/conftest.py
> +    return False
I'm not clear why you need the regex here; it's effectively just removing the `[` and `]` for the comparison. The doctsring says the function ignores the datetime, so in that case perhaps just split on the first `]`, discard the first substring and compare the second?

The substituted `history.value` can be hoisted out of the loop; it's value doesn't change with each pass.

Minor: 
```
if all( ... ):
  return True
```
is the same as:
```
return all( ... )
```

2023-05-11 11:43 UTC, kjsanger commented on tests/test_ont.py
> +        num_found, num_updated, num_errors = update.update_secondary_metadata(
```num_found, num_updated, num_errors``` are assigned to, but not checked. I think better to either not assign them (so make it clear that the return values are not tested), or test them.

2023-05-11 14:20 UTC, kjsanger requested changes

2023-05-11 14:20 UTC, kjsanger commented on tests/conftest.py
> +    )
I think you have some redundancy in the return value; `all( ... )` returns a boolean, so wrapping that in a list and calling `any` isn't needed.

2023-05-11 14:28 UTC, mksanger commented on tests/conftest.py
> +    )
The bracket is in the wrong place, but it was written for cases where there are multiple `_history` avus, in which case you would not want to return the first false from an `all` call.  I suppose that that is no longer entirely necessary, since I ended up not writing any tests where multiple _history avus are expected to be present...

2023-05-12 14:10 UTC, kjsanger approved these changes

2023-05-12 14:10 UTC, merged