Add new study groups for human
wtsi-npg/npg-irods-python pull request #235
Opened 2024-01-12 13:26 UTC by zb32

I've implemented this so a irods group of ss_<studyid>_human get's added when the component has a subset of "human". I'm not sure if this is the best way to do it so open to feedback :D 

I was also thinking for line 249 in `src/npg_irods/illumina.py`
`elif any(c.contains_nonconsented_human() for c in components): # Illumina specific`
does It make sense to still implement it this was as now the logic for a subset of "human" and "xahuman" is different so maybe we make the distinction here and use two separate methods instead of have the logic inside the method? Hopefully that makes sense.

2024-01-16 15:32 UTC, kjsanger requested changes

2024-01-16 15:32 UTC, kjsanger commented on src/npg_irods/metadata/lims.py
> +        if sample.consent_withdrawn or (seq is not None and seq.value == "xahuman")
Enum values should be compared directly, no need to compare to their string representation.

2024-01-16 15:32 UTC, kjsanger commented on src/npg_irods/metadata/lims.py
> +        seq: Sequencing terminology, unique to illumina
The docstring is incorrect here.

2024-01-16 15:32 UTC, kjsanger commented on src/npg_irods/metadata/lims.py
> +        if sample.consent_withdrawn or (seq is not None and seq.value == "xahuman")
So I think you mean the `SeqSubset` Enum here.

If consent is withdrawn, it's game over and the permissions are known at that stage in the function, so that's a strong candidate for an early `return`, rather than checking the same thing later.

You've added behaviour for `SeqSubset.XAHUMAN`, but I don't see that tested. Did you intend to omit `SeqSubset.YHUMAN`?

2024-01-16 15:32 UTC, kjsanger commented on src/npg_irods/ont.py
> +        acl.extend(make_sample_acl(None, fc.sample, fc.study, zone=zone))
The probably isn't a good place to be managing the ACL because a few lines later there's other code which already manages consent and human data;

https://github.com/wtsi-npg/npg-irods-python/blob/3bc4eee4a72c2ad6ea58f568983074ccaff21eff/src/npg_irods/illumina.py#L246-L253

2024-01-16 15:32 UTC, kjsanger commented on src/npg_irods/ont.py
> +        acl.extend(make_sample_acl(None, fc.sample, fc.study, zone=zone))
(I will check that the line `xahu_update = update_permissions(item, acl)` is doing the right thing - as it's the same as the last case, except for the logging, it's making me suspicious!)

2024-01-18 12:59 UTC, zb32 commented on src/npg_irods/ont.py
> +        acl.extend(make_sample_acl(None, fc.sample, fc.study, zone=zone))
Before it was just removing the AC group with the `ensure_consent_withdrawn` method. I could create another method in the LIMS class that is Illumina specific. Or should we get rid of this elif statement and have it fall into the regular update permissions. Or I could update `contains_nonconsented_human()` to remove a `human` subset from it and keep it as `ensure_consent_withdrawn` for `xahuman`? I think the last option might be the best one.

2024-01-18 14:24 UTC, zb32 commented on src/npg_irods/metadata/lims.py
> +    if seq is not None and seq.value == "human":
I should have wrote `SeqSubset` as that's what's being passed to this method in the code for Illumina. I've changed this now. Sometimes this is None when not set and it was causing a `AttributeError`.

2024-01-18 14:39 UTC, zb32 commented on src/npg_irods/metadata/lims.py
> +        if sample.consent_withdrawn or (seq is not None and seq.value == "xahuman")
`SeqSubset.XAHUMAN` was in the `contains_unconsented_human` method so I wanted to make sure it remained the same and removed access

2024-01-18 14:52 UTC, kjsanger commented on src/npg_irods/ont.py
> +        acl.extend(make_sample_acl(None, fc.sample, fc.study, zone=zone))
`ensure_consent_withdrawn` is specifically for when donors withdrawn consent for their data to be used, which is distinct from the case where there's human DNA in the results which need to be separated. Consent withdrawn is a much more serious and final event - the data are closed to all access (which is what that function does) before being fully deleted in a follow-up step. That includes data separated as `human`, `xahuman` and so on; it will all get deleted.

If you look here https://github.com/wtsi-npg/npg-irods-python/blob/f0ebca831fae65c09e92772887b3e9b0b0684cd5/src/npg_irods/illumina.py#L249

there's a test for "non-consented" human DNA. That's not a great same for it, but that's what we call human data that is there as a contaminant of another species (it's not "consent withdrawn" because there was no specific consent in the first place). I said earlier that I was dubious about following line
and I'm pretty sure it's wrong. That's a good place to put a new function that adjusts the ACL appropriately for `human`, `xahuman` etc.

In general don't change predicates (pure functions that return a boolean) to add side-effects that change state somewhere e.g. `contains_non_consented_human`. Functions should do one thing and ideally that thing is obvious from thewir name, so perhaps add a new function to make the ACL change you need and put it in the block guarded by that predicate.

2024-01-18 17:00 UTC, zb32 commented on src/npg_irods/metadata/lims.py
> +        if sample.consent_withdrawn or (seq is not None and seq.value == "xahuman")
also https://github.com/wtsi-npg/npg-irods-python/blob/f0ebca831fae65c09e92772887b3e9b0b0684cd5/src/npg_irods/illumina.py#L246
it looks like it's checking previously if consent is withdrawn so I was wondering if something different is happening here?

2024-01-25 10:25 UTC, kjsanger requested changes
The main thing still needed is that the existing test for xahuman should be updated to test for the new permissions. It currently just tests that the old permissions are removed (see `test_updates_xahuman_permissions_mx`).

2024-01-25 10:25 UTC, kjsanger commented on src/npg_irods/illumina.py
> +            acl.extend(acl_fn(fc.sample, fc.study, c.subset, zone=zone))
As `subset` is now a keyword argument, it's best called like that i.e. `subset=c.subset`

2024-01-25 10:25 UTC, kjsanger commented on src/npg_irods/metadata/lims.py
> +        subset: Subset of sequence reads
Can you put the `Args:` docs in order? With `subset` being listed first, it looks at first like it's the first positional argument.

2024-01-25 10:25 UTC, kjsanger commented on tests/test_illumina.py
> +    @m.it("Update managed access permissions to restricted human access group")
Minor: Update -> Updates, so that the line reads `it(Updates ...`)

2024-01-25 10:52 UTC, kjsanger commented
One more thing that I forgot - all the modified files will need their copyright statement (if they have one) updated to add the year 2024 to the list of years.

2024-01-25 11:09 UTC, zb32 commented
> The main thing still needed is that the existing test for xahuman should be updated to test for the new permissions. It currently just tests that the old permissions are removed (see `test_updates_xahuman_permissions_mx`).

I think David said that the '_human' group should just be used for the human subset

2024-01-25 11:38 UTC, kjsanger commented
> > The main thing still needed is that the existing test for xahuman should be updated to test for the new permissions. It currently just tests that the old permissions are removed (see `test_updates_xahuman_permissions_mx`).
> 
> I think David said that the '_human' group should just be used for the human subset

I checked JIRA and there's no mention of xahuman, so I agree - let's interpret that at literally just `human` -> `_human` for the scope.

2024-01-25 13:00 UTC, merged