Add general metadata script
wtsi-npg/npg-irods-python pull request #254
Opened 2024-02-23 11:51 UTC by zb32

Create new script to add secondary metadata for newer platforms.

2024-02-23 16:52 UTC, mgcam commented on src/npg_irods/utilities.py
> +            elif rods_item.metadata(TrackedSample.ID) != sample_id:
Both study and sample id can be different, so have to check for both independently in order to provide a comprehensive log message. In case of a mismatch the log message should clearly state what file/collection was considered and the action, ie skipped.

2024-02-23 17:11 UTC, mgcam commented on src/npg_irods/utilities.py
> +    query = sess.query(Study).distinct().filter(Study.id_study_lims == id)
`distinct` seems misplaced here. Not sure what it achieves. We really want to retrieve one record or error.

2024-02-23 17:12 UTC, mgcam commented on src/npg_irods/utilities.py
> +        study_id: A sampple_id in MLWH
sampple_id ->sample_id

2024-02-23 18:21 UTC, nerdstrike reviewed
The good news is you've gotten test harness working for you.

I believe the docstrings need enhancing/correcting, and the singular test doesn't fill me with confidence. I am particularly concerned about what happens if metadata on a collection is partially altered, and either the script help should declare that it is additive or that it also replaces existing terms.

2024-02-26 12:42 UTC, kjsanger commented on src/npg_irods/cli/apply_general_study_metadata.py
> +Takes a StudyID and iRods collection or data object and applies the study metadata from MLWH to it.
Minor: "Study ID" or "study ID" (space), "iRODS" capitalisation.

2024-02-26 12:45 UTC, kjsanger commented on src/npg_irods/cli/apply_general_study_metadata.py
> +    help="Print to output those paths that require repair, where the repair failed. "
I think references to checks/repairs are copy-paste errors from other scripts - can be fixed by subsituting the correct verb(s).

2024-02-26 12:53 UTC, kjsanger commented on src/npg_irods/utilities.py
> +                log.warn("Tracked study ID in MLWH is", TrackedStudy.ID)
The library uses structured logging, so there shouldn't be any positional args except the message (which should be complete i.e. not expect things to be appended to it to make sense.

For conventions see e.g. https://github.com/wtsi-npg/npg-irods-python/blob/3718c65acb993bd88d48957aad359a919980a34e/src/npg_irods/utilities.py#L297

The collection or data object path should appear as `path`, the item number in the enumeration should appear as `item`. Other parameters should be named approriately e.g. `study_id`. This way, log consumers don't have to try to parse free-text log messages.

2024-02-26 13:01 UTC, kjsanger commented on src/npg_irods/utilities.py
> +    query = sess.query(Study).distinct().filter(Study.id_study_lims == id)
Agree - one motivation for making these small queries into their own functions would be to include those checks in the function, to save the caller doing it.

2024-02-26 13:03 UTC, kjsanger commented on src/npg_irods/utilities.py
> +def find_study_by_study_id(sess: Session, id: Study.id_study_lims) -> Study:
> I don't think this function has anything to do with "iRODS utilities". This module is already massive.

Simple `find_<X>_by_id` things could perhaps go in `db/mlwh`?

2024-02-26 14:13 UTC, zb32 commented on src/npg_irods/utilities.py
> +    """ """
![image](https://github.com/wtsi-npg/npg-irods-python/assets/113424561/7eb6ba40-5ebf-4da6-8680-646aed630525)

2024-02-26 14:14 UTC, zb32 commented on src/npg_irods/utilities.py
> +    """ """
I forgot to add the description will do now! 😅

2024-02-26 14:30 UTC, zb32 commented on src/npg_irods/cli/apply_general_study_metadata.py
> +    help="Print to output those paths that require repair, where the repair failed. "
Was a copy/paste error sorry

2024-03-01 16:29 UTC, zb32 commented on src/npg_irods/utilities.py
> +    secondary_metadata.extend(make_study_metadata(study))
It returns all the AVUs for what's available in MLWH

2024-03-04 18:16 UTC, nerdstrike requested changes
Round 2 - the bettering!

2024-03-04 18:16 UTC, nerdstrike commented on src/npg_irods/cli/apply_general_study_metadata.py
> +        num_errors=num_errors,
So I guess this number is always zero.

2024-03-05 12:11 UTC, zb32 commented on src/npg_irods/db/mlwh.py
> +    query = sess.query(Study).filter(Study.id_study_lims == id)
good spot! :spot: :D

2024-03-05 15:13 UTC, nerdstrike commented
Did you intend to replace the sqlalchemy v1 code? It's still there. It'll work at the moment, but ultimately break.

2024-03-05 15:54 UTC, zb32 commented
> Did you intend to replace the sqlalchemy v1 code? It's still there. It'll work at the moment, but ultimately break.

I thought I replaced it but it didn't get added :doge: re-added and pushed

2024-03-05 16:42 UTC, merged