Feature: extend barcode collection search
wtsi-npg/npg-irods-python pull request #323
Opened 2024-06-10 09:08 UTC by marcomoscasgr

Metadata updates works on ONT paths uploaded from the instrument to iRODS. This PR will add:
- recursive search of barcode collections on which apply metadata for rebasecalled data
- new tests for old and new rebasecalled and plexed data
- two new test dataset: old and new plexed and rebasecalled folder structures
- test updates for mlwh queries and html meta-report file

2024-06-17 13:14 UTC, kjsanger requested changes

2024-06-17 13:14 UTC, kjsanger commented on tests/ont/conftest.py
> +            id_flowcell_lims=f"flowcell{sl + fc_start :0>3}",
Black doesn't catch this, but PEP 8 says there should not be whitespace before the `:` on the format string

2024-06-17 13:14 UTC, kjsanger commented on tests/ont/conftest.py
> +            id_flowcell = f"flowcell{slot + 200 :0>3}"
As above (and more below).

2024-06-17 13:14 UTC, kjsanger commented on tests/ont/test_metadata_update.py
> +        actual_tag_identifies = [
Typo

2024-06-17 14:33 UTC, kjsanger commented on src/npg_irods/ont.py
> +                    "No barcode sub-collection", path=str(bpath), tag_identifier=tag_id
I'm pretty sure the `str()` call is unnecessary (also on other cases above) and it reads better without.

2024-06-17 14:43 UTC, marcomoscasgr commented on src/npg_irods/ont.py
> +                    "No barcode sub-collection", path=str(bpath), tag_identifier=tag_id
The last push includes this change.

2024-06-17 15:00 UTC, marcomoscasgr commented on src/npg_irods/ont.py
> +                    "No barcode sub-collection", path=str(bpath), tag_identifier=tag_id
I have just spotted the other in the string above that. Thanks

2024-06-18 11:08 UTC, kjsanger approved these changes
There's a lot of commits here, so I'll squash them to make the change clearer

2024-06-18 11:09 UTC, merged