Backfill scripts
wtsi-npg/npg-irods-python pull request #4
Opened 2022-07-27 11:41 UTC by mksanger

Add script to backfill illumina locations in the seq_irods_product_locations table.

2022-07-27 12:13 UTC, mgcam commented on bin/backfill_illumina_locations.py
> +LOADING_SCRIPT = "/software/npg/current/bin/npg_irods_locations2ml_warehouse"
I would not load at the same time as doing data retrieval from iRODS. It is perfectly OK and, in fact, less error prone, to collect all data, inspect, and then to load outside the scope of this script.

If you were to load within this script, any environment variables should be set outside the script. The only information this script would need is the name of the Perl script to run.

2022-07-27 15:49 UTC, mgcam commented on src/npg_irods/mlwh_locations/illumina.py
> +                raise MissingMetadataError(
For old runs there might be cases when id_product metadata is not set. Better to log a warning, continue. If these are very old data, we will just disregard this warning. For recent data we will investigate.

2022-07-27 15:54 UTC, mgcam commented
I wonder whether we need to include tag zero and tag 888 data. Probably not. Is it possible to only select the data with tagret=1 metadata (have to check that that will exclude this kind of data)?

2022-07-27 17:02 UTC, mgcam commented
Any path containing `ranger` should be excluded.

2022-07-27 17:14 UTC, mgcam commented on src/npg_irods/mlwh_locations/illumina.py
> +                    product["pipeline_name"] = ALT_PROCESS
We need the value of the `alt_process` metadata here. Might prepend with some short prefix if the column size allows. Have to research how long the values are or just preventively extend the size of the column

2022-07-27 17:16 UTC, mgcam commented on src/npg_irods/mlwh_locations/illumina.py
> +                    product["pipeline_name"] = ALT_PROCESS
We might consider getting the data out to see what we have there, then decide.

2022-07-27 17:21 UTC, mgcam commented on misc/illumina_locations_backfill_prep.md
> +  JOIN iseq_run_status AS irs
can we join to the dict table so that we could make a selection on the description of the status rather than on the id. Also, we have quite a few runs, where the final status is 'run archived'. We should check this.

2022-07-27 17:25 UTC, kjsanger requested changes
The functions like `generate_files` and `find_products` should have tests that demonstrate they do the right thing. Only needs a token amount of test data.

2022-07-27 17:25 UTC, kjsanger commented on src/npg_irods/mlwh_locations/illumina.py
> +def find_products(coll: Collection, processes: int, log: Any) -> List[dict]:
Normally you'd have a logger e.g. per module and not pass explictly. If you do this you could see log messages from one module appearing to be messages from another.

2022-07-27 17:26 UTC, mgcam commented on misc/illumina_locations_backfill_prep.md
> +  irlm.instrument_model
This works because the instrument model is always the same for all lanes. The `distinct` clause applies to the `id_run` column, while what in general case would be the value for instrument_model is not deterministic.

2022-07-28 10:26 UTC, mksanger commented on src/npg_irods/mlwh_locations/illumina.py
> +                    product["pipeline_name"] = ALT_PROCESS
I thought that we had decided not to specify what the alt process was:
```
The name of the pipeline used to produce the data, values are: npg-prod, npg-prod-alt-process, cellranger, spaceranger, ncov2019-artic-nf
```
(from the comment on the pipeline_name field)
Not that we have anything other than npg-prod in that column so far...

2022-07-28 10:29 UTC, mksanger commented on src/npg_irods/mlwh_locations/illumina.py
> +                    product["pipeline_name"] = ALT_PROCESS
Happy to change that if that is the consensus, but we should probably also change the comment (and possibly the file generation in run publisher) if we do.

2022-07-28 14:14 UTC, mgcam commented on src/npg_irods/mlwh_locations/illumina.py
> +            obj.name.split(".")[-1] == ext
Filtering out phix, human. There might be some other splits as well. We might be better off relying on 'subset' metadata being undefined.

2022-08-01 08:49 UTC, mksanger commented on src/npg_irods/mlwh_locations/illumina.py
> +                    product["pipeline_name"] = ALT_PROCESS
Changed to alt_<process_metadata_value>

2022-08-02 15:50 UTC, kjsanger requested changes

2022-08-02 15:50 UTC, kjsanger commented on src/npg_irods/mlwh_locations/illumina.py
> +                    (meta.attribute == "tag_index" and meta.value == "0")
Things like `meta.attribute == "tag_index" and meta.value == "0"` can be improved by having a descriptive function so that it's clear to the reader why this test is being done.

e.g. (this is just an example and doesn't mean it has to have this signature):

```
def is_tag_zero_data(obj: DataObject) -> bool:
    """Return true if, according to its metadata, obj contains data assigned to
    multiplex tag "0" i.e. reads that could not be assigned a real tag during
    de-multiplexing.

    Args:
       obj: data object whose metadata to test
    """
    return AVU(SeqConcept.TAG_INDEX, "0") in obj.metadata()
```

So most of the work is in naming the function (which still isn't perfect in this example) and in the docstring.

Also, better to use existing metadata Enums where possible in AVU building, rather than bare strings. Saves on typos and they can also have docstrings that offer interactive help when coding. The Enums are incomplete as yet, but some are there.

2022-08-02 15:50 UTC, kjsanger commented on src/npg_irods/mlwh_locations/illumina.py
> +            for meta in obj.metadata():
The tests don't cover anything in the block under ` for meta in obj.metadata():` and there's quite a lot of behaviour in there.

2022-08-02 16:20 UTC, kjsanger commented on tests/test_illumina_backfill.py
> +        return self.d
Have you got some docs e.g. pytest issue or explanation of the effect that this fixes? Do we know what exactly is deadlocking?

2022-08-02 16:28 UTC, mksanger commented on tests/test_illumina_backfill.py
> +        return self.d
This issue is the most comprehensive one I could find, but there are multiple searchable: https://github.com/pytest-dev/pytest/issues/958. (Closed as someone else's problem)

It looks like it isn't specifically pytest, but its use of artefacts created by pip and/or setuptools.

2022-08-02 16:35 UTC, kjsanger commented on tests/test_illumina_backfill.py
> +        return self.d
Have you tried running the only the tests in this module? I've run them repeatedly and can't get them to hang (at 238be14b33196e13f58a3ef63d9fc9a176e95bb7). Which version of Python is this?

2022-08-02 16:37 UTC, mksanger commented on tests/test_illumina_backfill.py
> +        return self.d
238be14 is before the hanging test was added

2022-08-02 16:37 UTC, mksanger commented on tests/test_illumina_backfill.py
> +        return self.d
I'm running on 3.10.5

2022-08-02 17:47 UTC, kjsanger commented on src/npg_irods/mlwh_locations/illumina.py
> +            for meta in obj.metadata():
Interesting - when I ran the tests, the coverage report didn't have anything over those lines. I will check again

2022-08-02 19:49 UTC, kjsanger commented on src/npg_irods/mlwh_locations/illumina.py
> +            for meta in obj.metadata():
Thanks, I see now. The coverage report is wrong and is missing that these lines were hit.

2022-08-02 19:54 UTC, kjsanger commented on tests/test_illumina_backfill.py
> +        return self.d
238be14b33196e13f58a3ef63d9fc9a176e95bb7 is the only commit that I have before c4682910ba359bf475e0ad2d2bf4871c327c7580 (which includes the mock `ApplyResult`. Forced update? Is there a commit that still shows the problem? We should keep a reproducer of the problem because having a mock soley there to work around a deadlock is tech debt that we should be careful of. It will have to be understood/resolved at some point.

2022-08-03 09:17 UTC, mksanger commented on tests/test_illumina_backfill.py
> +        return self.d
Yes, forced update, but I expect I can create a reproducer relatively easily

2022-08-03 10:05 UTC, kjsanger commented on src/npg_irods/mlwh_locations/illumina.py
> +    """
By the way, I wouldn't want to block on this. It's a suggestion.

2022-08-03 10:07 UTC, mksanger commented on src/npg_irods/mlwh_locations/illumina.py
> +    """
It is done

2022-08-03 10:07 UTC, kjsanger commented on src/npg_irods/mlwh_locations/illumina.py
> +    """
I just saw ... great!

2022-08-03 15:45 UTC, mksanger commented on tests/test_illumina_backfill.py
> +        return self.d
The reproducer has been added

2022-08-03 17:51 UTC, kjsanger commented on tests/test_illumina_backfill.py
> +        return self.d
If I comment out the `@m.xfail` to get the ignord test to run, it fails with a type error, rather than a timeout:

```
tests/test_illumina_backfill.py:125 (TestExtractProducts.test_product_result_using_pool)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
TypeError: applied_function() takes 1 positional argument but 5 were given
"""

The above exception was the direct cause of the following exception:

self = <test_illumina_backfill.TestExtractProducts object at 0x106227310>
illumina_products = PurePosixPath('/testZone/home/irods/test/Users/kdj/Development/python/npg-irods-python/tests/tmp/test_product_result_using_pool0/mlwh_locations')

    def test_product_result_using_pool(self, illumina_products):
        expected = [
            {
                "seq_platform_name": "illumina",
                "pipeline_name": illumina.NPG_PROD,
                "irods_root_collection": f"{illumina_products}/12345",
                "irods_data_relative_path": "12345#1.cram",
                "id_product": "31a3d460bb3c7d98845187c716a30db81c44b615",
            }
        ]
        with Pool(1) as p:
            results = [p.apply_async(applied_function, product) for product in expected]
>           assert illumina.extract_products(results, timeout=10) == expected

tests/test_illumina_backfill.py:138: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/npg_irods/mlwh_locations/illumina.py:173: in extract_products
    product = result.get(timeout=timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <multiprocessing.pool.ApplyResult object at 0x106230340>, timeout = 10

    def get(self, timeout=None):
        self.wait(timeout)
        if not self.ready():
            raise TimeoutError
        if self._success:
            return self._value
        else:
>           raise self._value
E           TypeError: applied_function() takes 1 positional argument but 5 were given

/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py:771: TypeError
```

2022-08-03 18:12 UTC, kjsanger commented on tests/test_illumina_backfill.py
> +        assert illumina.extract_products(results, timeout=10) == expected
Could this be hanging because `illumina.extract_products` is being called after the pool is closed? I think line 138 is missing an indent.

Adding the indent and the `get` doesn't time out. However, the call to `apply_async` then reports an invalid number of arguments:

```
src/npg_irods/mlwh_locations/illumina.py:173: in extract_products
    product = result.get(timeout=timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <multiprocessing.pool.ApplyResult object at 0x105d242b0>, timeout = 10

    def get(self, timeout=None):
        self.wait(timeout)
        if not self.ready():
            raise TimeoutError
        if self._success:
            return self._value
        else:
>           raise self._value
E           TypeError: applied_function() takes 1 positional argument but 5 were given
```

Changing the call to `apply_async` to wrap the argument, the test passes without timing out:

```
        with Pool(1) as p:
            results = [
                p.apply_async(applied_function, (product,)) for product in expected
            ]
            assert illumina.extract_products(results, timeout=10) == expected
```

2022-08-18 14:13 UTC, merged