Feature: ONT metadata updates
wtsi-npg/npg-irods-python pull request #78
Opened 2023-02-28 13:01 UTC by marcomoscasgr

This PR will add:
- `update-ont-metadata` script to run ONT metadata updates within a time window until the current date (since 14 days before by default)
- a logging configuration file example `logging_syslog.conf` built to log ERROR level messages to syslog
- a test in `test_ont.py` that calls the script with `subprocess` and essential options

2023-03-01 10:02 UTC, marcomoscasgr commented
I added `tests/data/logging_syslog.conf` as an example of how to set up a log dispatcher for syslog in python, it is not used by the tests. Should I keep it in the repository?

2023-03-01 13:49 UTC, kjsanger commented
> I added `tests/data/logging_syslog.conf` as an example of how to set up a log dispatcher for syslog in python, it is not used by the tests. Should I keep it in the repository?

It shouldn't be under tests is the tests don't use it. However, there should be documentation so that people know how to create a log config, so it's still useful as an example.

2023-03-03 09:59 UTC, kjsanger requested changes

2023-03-03 10:26 UTC, marcomoscasgr commented on scripts/update-ont-metadata
> +)
Yes, I better choose always the long-form with no shortname

2023-03-03 14:00 UTC, marcomoscasgr commented on tests/test_ont.py
> +
To test the script, Should I test only the return code of subprocess?

2023-03-03 14:20 UTC, kjsanger commented on tests/test_ont.py
> +
The script essentially contain a single method call to a tested method. I don't think we gain anything by maintaining tests for them.

2023-03-03 14:25 UTC, marcomoscasgr commented on tests/test_ont.py
> +
ok, I will remove the test at this point.

2023-03-03 14:50 UTC, marcomoscasgr commented on scripts/update-ont-metadata
> +        if args.begin_date:
I added a default `datetime` instance directly in the `add_argument` method of `argparse`. That should be a clean way to do it.

2023-03-03 15:38 UTC, merged